#Created by @cativo23 <cativo23.kt@gmail.com>

version: '3'

services:
  api:
    container_name: life-changers-api
    image: life-changers/api:latest
    build:
      context: ./docker
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    ports:
      - "3333:3000"
      - "5555:5555"
    volumes:
      - .:/usr/src/app
    networks:
      - life-changers
      - web
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.life.rule=Host(`life.${DOMAIN}`)"
    - "traefik.http.routers.life.entrypoints=websecure"
    - "traefik.http.services.life.loadbalancer.server.port=3000"
    - "traefik.http.routers.life.service=life"
    - "traefik.http.routers.life.tls.certresolver=lets-encrypt"
    - "traefik.http.routers.life.tls=true"
    - "traefik.docker.network=web"
  
  mysql:
    container_name: life-changers-db
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - 'life-changers-mysql:/var/lib/mysql'
    networks:
      - life-changers
    labels:
    - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  mysql-test:
    container_name: life-changers-db-test
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - 'life-changers-mysql-test:/var/lib/mysql'
    networks:
      - life-changers
    labels:
    - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  life-changers:
    driver: bridge
    name: life-changers
  web:
    external: true

volumes:
  life-changers-mysql:
    driver: local
  life-changers-mysql-test:
    driver: local